import {
  PayCircleOutlined,
  ShoppingCartOutlined,
  MessageOutlined,
  TeamOutlined,
  UserOutlined,
  DashboardOutlined,
  ApiOutlined,
  CameraOutlined,
  EditOutlined,
  CodeOutlined,
  LineOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  PercentageOutlined,
  RetweetOutlined,
  DollarOutlined,
  CheckOutlined,
  WalletOutlined,
  ArrowLeftOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  QuestionCircleOutlined,
  DoubleLeftOutlined,
  LeftOutlined,
  RightOutlined,
  DoubleRightOutlined,
  AppstoreOutlined,
  BarsOutlined
} from '@ant-design/icons';

const Iconmap: { [unit: string]: object } = {
  payCircleO: <PayCircleOutlined />,
  shoppingCart: <ShoppingCartOutlined />,
  cameraO: <CameraOutlined />,
  lineChart: <LineOutlined />,
  codeO: <CodeOutlined />,
  areaChart: <AreaChartOutlined />,
  barChart: <BarChartOutlined />,
  message: <MessageOutlined />,
  team: <TeamOutlined />,
  dashboard: <DashboardOutlined />,
  user: <UserOutlined />,
  api: <ApiOutlined />,
  edit: <EditOutlined />,
  percent: <PercentageOutlined />,
  retweet: <RetweetOutlined />,
  doller: <DollarOutlined />,
  check: <CheckOutlined />,
  wallet: <WalletOutlined />,
  back: <ArrowLeftOutlined />,
  before: <LeftOutlined />,
  next: <RightOutlined />,
  doubleBefore: <DoubleLeftOutlined />,
  doubleNext: <DoubleRightOutlined />,
  question: <QuestionCircleOutlined />,
  column: <AppstoreOutlined />,
  bar: <BarsOutlined />
};

export default Iconmap;
